apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-backend
  labels:
    app: nodejs-backend
  namespace: default
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: nodejs-backend
  template:
    metadata:
      labels:
        app: nodejs-backend
    spec:
      containers:
        - name: nodejs-backend
          image: habibsellami3/tp2devops:main
          ports:
            - containerPort: 8080 # Port your Node.js app listens on
          env:
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "8080"
            - name: APP_URL
              value: "http://localhost:8080"
            - name: JWT_SECRET
              value: "redis"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "redis"
            - name: HTTPS_ENABLED
              value: "false"

          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: myregistrykey
